#include <gdt.h>

__attribute__((section(".gdt_zone")))
GDT_entry GDT[] = {
	GDT_ENTRY(0, 0, 0, 0), // Null segment

	//Kernel code segment
	GDT_ENTRY(0,
			0xFFFFF,
			GDT_ACCESS_PRESENT | GDT_ACCESS_RING0 | GDT_ACCESS_CODE_SEGMENT | GDT_ACCESS_CODE_READABLE,
			(GDT_FLAG_32_BIT | GDT_FLAG_GRANULARITY_PAGE)
		),

	//Kernel data segment
	GDT_ENTRY(0,
			0xFFFFF,
			GDT_ACCESS_PRESENT | GDT_ACCESS_RING0 | GDT_ACCESS_DATA_SEGMENT | GDT_ACCESS_DATA_WRITABLE,
			(GDT_FLAG_32_BIT | GDT_FLAG_GRANULARITY_PAGE)
		),

	//Kernel Stack Segment
	GDT_ENTRY(0,
			0xFFFFF,
			GDT_ACCESS_PRESENT | GDT_ACCESS_RING0 | GDT_ACCESS_DATA_SEGMENT | GDT_ACCESS_DATA_WRITABLE,
			(GDT_FLAG_32_BIT | GDT_FLAG_GRANULARITY_PAGE)
		),

	//User code segment
	GDT_ENTRY(0,
			0xFFFFF,
			GDT_ACCESS_PRESENT | GDT_ACCESS_RING3 | GDT_ACCESS_CODE_SEGMENT | GDT_ACCESS_CODE_READABLE,
			(GDT_FLAG_32_BIT | GDT_FLAG_GRANULARITY_PAGE)
		),

	//User data segment
	GDT_ENTRY(0,
			0xFFFFF,
			GDT_ACCESS_PRESENT | GDT_ACCESS_RING3 | GDT_ACCESS_DATA_SEGMENT | GDT_ACCESS_DATA_WRITABLE,
			(GDT_FLAG_32_BIT | GDT_FLAG_GRANULARITY_PAGE)
		),

	//User Stack Segment
	GDT_ENTRY(0,
			0xFFFFF,
			GDT_ACCESS_PRESENT | GDT_ACCESS_RING3 | GDT_ACCESS_DATA_SEGMENT | GDT_ACCESS_DATA_WRITABLE,
			(GDT_FLAG_32_BIT | GDT_FLAG_GRANULARITY_PAGE)
		),
};
